name: Android Dumpyara

on:
  workflow_dispatch:
    inputs:
      FIRMWARE_URL:
        description: 'Firmware URL (Stock Firmware download link.)'
        required: true
        default: 'https://06-samsung.cloud/v2/IxJCDiMnLjMJFyELAyxBIzQnNAYzNh4lFzssIDs2ByAzMUEgOzEUQDMQMCMBOyw/FxcwGjMWLywhFi81MyQiOQ8IHwUuLyE5DSUhIzQWKQASOCwdLgs0FB4WMwQ7AzQGLywzFw0LFUA8CwcxCRchEDQ7KQczQCkEDTA+OwNAKQY0Cy8tNAchJy84BkIjCyI/Iws8MQEWCDAeCw0xCREHOTQbIyshAD4OIQAGLC44Hiw0ER4OMiUzLDIlDSs8AD4fJhsGOg8HCkA8AywnCRc+Di8LBxAzBy4RDxYpKTwkHjUeBylCJgceKTIXIUAJER4OMi8+AwMSMDsjJBU5ODAeBzssPjsjJBU5MwcpAx4IHi8zFh4mIREHCwklAgI0GwZCDwcpCC47AgINMDMXHgcvEQMXBT8SLwoADSweOh42ITEPESwEFyweOjwXOwYmGzkGHgs0AB4DIzABFjQG'
      DEVICE_NAME:
        description: 'Device Codename (Codename, not the shipped device name.)'
        required: true
        default: 'gta2swifi'
      VENDOR_NAME:
        description: 'Vendor Name (Manufacturer or brands.)'
        required: true
        default: ''
        type: choice
        options:
        - xiaomi
        - samsung
        - realme
        - oppo
        - lenovo
        - motorola
        - asus
        - itel
        - tecno
        - infinix
        - unknown
      FIRMWARE_NAME:
        description: 'Firmware Name (Exact firmware name, the better.)'
        required: true
        default: 'Samfw.com_SM-T380_SER_T380DXS4CUD3_fac'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    steps:
    - name: Display Run Parameters
      run: |
        echo "::group::User Environment Variables"
        echo "FIRMWARE_URL: ${{ github.event.inputs.FIRMWARE_URL }}"
        echo "DEVICE_NAME: ${{ github.event.inputs.DEVICE_NAME }}"
        echo "VENDOR_NAME: ${{ github.event.inputs.VENDOR_NAME }}"
        echo "FIRMWARE_NAME: ${{ github.event.inputs.FIRMWARE_NAME }}"
        echo "TARGET REPOSITORY: https://gitlab.com/firmware-dump/android_dump_${{ github.event.inputs.VENDOR_NAME }}_${{ github.event.inputs.DEVICE_NAME }}.git"
        echo "::endgroup::"
 
    - name: Check Out
      uses: actions/checkout@v3.1.0

#    - name: Prepare the environment
#      run: |
#        sudo apt install unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack arj cabextract rename
#        sudo apt install liblzma-dev python3-pip brotli lz4
#        pip install backports.lzma protobuf pycrypto twrpdtgen extract-dtb pycryptodome

    - name: Clone Extractor
      run: |
        mkdir workspace
        cd workspace
        git clone https://github.com/AndroidDumps/dumpyara.git
        cd dumpyara
        sudo bash setup.sh
          
    - name: Run
      run: |
        cd workspace && cd dumpyara
        ./dumpyara.sh ${{ github.event.inputs.FIRMWARE_URL }}
      continue-on-error: true

    - name: Run
      run: |
        cd workspace && cd dumpyara
        ./dumpyara.sh ${GITHUB_WORKSPACE}/workspace/dumpyara/input/${{ github.event.inputs.FIRMWARE_NAME }}.zip
      continue-on-error: true

    - name: Pushing to as Repository
      run: |
        cd workspace && cd dumpyara/working/${{ github.event.inputs.FIRMWARE_NAME }}
        rm -rf .git
        git init
        git config http.postBuffer 524288000
        git config --global user.name "Carlo Dee"
        git config --global user.email "carlodee.official@gmail.com"
        git branch -M ${{ github.event.inputs.FIRMWARE_NAME }}
        git add .
        git commit -m "Initial commit: Import from ${{ github.event.inputs.FIRMWARE_NAME }}."
        git remote add origin https://${{ secrets.gitlab_tokenName }}:${{ secrets.gitlab_userToken }}@gitlab.com/firmware-dump/android_dump_${{ github.event.inputs.VENDOR_NAME }}_${{ github.event.inputs.DEVICE_NAME }}.git
        git push -u origin ${{ github.event.inputs.FIRMWARE_NAME }}
        echo "Done pushing as a repository. You now have Full Android Dump."
