name: Android DumprX h

on:
  workflow_dispatch:
    inputs:
      FIRMWARE_URL:
        description: 'Firmware URL (Stock Firmware download link.)'
        required: true
        default: 'https://gauss-componentotacostmanual-in.allawnofs.com/remove-c43d47f2bde7aafd016de12f00964a8b/component-ota/23/02/16/c3cad989586d42d8834530fa367aa819.zip'
      DEVICE_NAME:
        description: 'Device Codename (Codename, not the shipped device name.)'
        required: true
        default: 'RMX3491-Tree'
      VENDOR_NAME:
        description: 'Vendor Name (Manufacturer or brands.)'
        required: true
        default: ''
        type: choice
        options:
        - xiaomi
        - samsung
        - realme
        - oppo
        - lenovo
        - motorola
        - asus
        - itel
        - tecno
        - infinix
        - unknown
      FIRMWARE_NAME:
        description: 'Firmware Name (Exact firmware name, the better.)'
        required: true
        default: 'c3cad989586d42d8834530fa367aa819'
      GITLAB_USERNAME:
        description: 'It could be just your gitlab username or group name that your own.'
        required: true
        default: 'firmware-dump'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-22.04
    steps:
    - name: Display Run Parameters
      run: |
        echo "::group::User Environment Variables"
        echo "FIRMWARE_URL: ${{ github.event.inputs.FIRMWARE_URL }}"
        echo "DEVICE_NAME: ${{ github.event.inputs.DEVICE_NAME }}"
        echo "VENDOR_NAME: ${{ github.event.inputs.VENDOR_NAME }}"
        echo "FIRMWARE_NAME: ${{ github.event.inputs.FIRMWARE_NAME }}"
        echo "FIRMWARE_NAME: ${{ github.event.inputs.GITLAB_USERNAME }}"
        echo "TARGET REPOSITORY: https://gitlab.com/${{ github.event.inputs.GITLAB_USERNAME }}/android_dump_${{ github.event.inputs.VENDOR_NAME }}_${{ github.event.inputs.DEVICE_NAME }}.git"
        echo "::endgroup::"
 
    - name: Check Out
      uses: actions/checkout@v3.1.0

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Clone Dumper
      run: |
        mkdir workspace
        cd workspace
        git clone https://github.com/cd-Crypton/DumprX.git
        cd DumprX
        sudo bash setup.sh
          
    - name: Run Dumper
      run: |
        cd workspace && cd DumprX
        ./dumper.sh ${{ github.event.inputs.FIRMWARE_URL }}

    - name: Clone AOSP DT Gen
      run: |
        cd workspace
        git clone https://github.com/sebaubuntu-python/aospdtgen.git
        cd aospdtgen && pip3 install .

    - name: Copy Files
      run: |
        cd workspace/DumprX/out/system/system/lib64
        rm -rf libm.so
        rm -rf lidl_android.so
        rm -rf lidl.so
        rm -rf libc.so
        cd bootstrap
        cp -n *.so ${GITHUB_WORKSPACE}/workspace/system/system/lib64/

    - name: Run AOSP DT Gen
      run: |
        cd workspace
        python3 -m aospdtgen -o lineageos ${GITHUB_WORKSPACE}/workspace/DumprX/out

    - name: Pushing to as Repository
      run: |
        cd workspace && cd aospdtgen/working
        rm -rf .git
        git init
        git config http.postBuffer 2097152000
        git config https.postBuffer 2097152000
        git config --global user.name "Carlo Dee"
        git config --global user.email "carlodee.official@gmail.com"
        git branch -M ${{ github.event.inputs.FIRMWARE_NAME }}
        git remote add origin https://${{ secrets.gitlab_tokenName }}:${{ secrets.gitlab_userToken }}@gitlab.com/${{ github.event.inputs.GITLAB_USERNAME }}/android_dump_${{ github.event.inputs.VENDOR_NAME }}_${{ github.event.inputs.DEVICE_NAME }}.git
        git add .
        git commit -m "Initial commit: Import from ${{ github.event.inputs.FIRMWARE_NAME }}."
        git push -u origin ${{ github.event.inputs.FIRMWARE_NAME }}
        echo "Done pushing as a repository. You now have Full Android Dump."
